### ISSUE TITLE
Using JS XML parser

### ISSUE THREAD

**Issue by mandric** [digidem/openrosa-formlist#1]
How do you feel about replacing node-expat for something that doesn't require node-gyp/C compilation? (speed vs convenience tradeoff)  Maybe https://github.com/Leonidas-from-XIV/node-xml2js?

**Comment by gmaclennan** [comment]
What is the use-case for avoiding node-gyp/C compilation? I had initially implemented something with sax.js but switched to node-expat for speed benefits, thinking that this would only be implemented on a server rather than needing to run in the browser.

**Comment by mandric** [comment]
Also might try https://github.com/isaacs/sax-js.  Our need is because we are deploying on a "thin" server, no python and no support for libexpat. ;-\  Still thinking a bit, but wanted your thoughts.

**Comment by mandric** [comment]
The port was quite easy. https://github.com/medic/openrosa-formlist/tree/sax

**Comment by gmaclennan** [comment]
Very cool @mandric, I wonder what the best way would be to maintain both versions? With such minimal changes it should be easy to keep them in sync as it is. I could update the README to point to this fork?

**Comment by mandric** [comment]
Also had the same question.  I haven't seen any projects that have a switch for different deps.  It would be cool to have a Makefile with a USE_SAX flag or something and we could pass to npm install somehow?  My immediate problem is solved at least, I just modified my package.json to install from the sax branch.  I'll close the issue but happy to continue discussion here.
